### ISSUE TITLE
Dependency on FOSUserBundle could be make optional

### ISSUE THREAD

**Issue by Agathver** [azine/email-bundle#18]
Looks like the dependency on FOSUserBundle can be made optional or abstracted such that the FOS Specific mail sending code may be used by custom implementations too. While FOSUserBundle may be the de-facto solution for Symfony auth system, it is not always the case.

**Comment by azine** [comment]
I guess it could.
Feel free to submitt a PR.

**Comment by Agathver** [comment]
There is just one dependency in the library: `Services/AzineTwigSwiftMailer.php` which depends on  `FOS\UserBundle\Mailer\TwigSwiftMailer` for about 3 lines of code.

Can we either provide it as example or make another bundle for it ?

**Comment by azine** [comment]
Yes sure, I don't see how you would do it, but I'm open for suggestions. 

I'm looking forward to seeing your suggestion in a PR (please include unit-tests where possible).
