### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by florin-r** [azine/email-bundle#2]
I'm trying to use the bundle to manage email notifications. Ca you please provide an example on how to send an email notification using a twig template.

Thank you.

**Comment by sadortun** [comment]
Hi @azine 

It would be very nice to have a couple of examples in the docs. 

Thanks!

**Comment by azine** [comment]
Hi @sadortun,

true. Unfortunately I have lots of other stuff going on as well... :-/ but it's on my todo-list.

Examples for what part would be your priority?

Cheers,

**Comment by sadortun** [comment]
Thanks for your quick feedback. 

Just a couple of quick example on how to use the bundle. You have great docs on how to configure it, but we cant see how to use it!

Example : https://github.com/stephpy/timeline-bundle/blob/master/Resources/doc/index.markdown#adding-a-timeline-action

**Comment by azine** [comment]
Ok. I'll try to find some time tomorrow.

Cheers

**Comment by azine** [comment]
I added some examples.

see https://github.com/azine/email-bundle/blob/master/USAGE_EXAMPLES.md

Let me know if you're looking for something more.

Cheers,
d.


2015-11-05 10:07 GMT+01:00 Dominik Businger <dominik.businger@gmail.com>:

> Ok. I'll try to find some time tomorrow.
>
> Cheers

**Comment by sadortun** [comment]
Thanks !
