### ISSUE TITLE
doc example problem

### ISSUE THREAD

**Issue by roozbeh360** [azine/email-bundle#3]
i do really want to send newsletter!
but how ?
i had try :

first of all the following line does not work :  
  immediateMailer:    "@swiftmailer.mailer.immediateMailer"

so it was replaced with : 
  immediateMailer:    "@mailer"
  OR
  # immediateMailer:    "@swiftmailer.mailer.immediateMailer"

then : 
  class User extends BaseUser implements \Azine\EmailBundle\Entity\RecipientInterface

the user class was implemented by RecipientInterface

then i had run : 
  emails:sendNewsletter

the result was : 
  Thu, 12 Feb 2015 08:37:34 +0100 : starting to send newsletter emails.
  Thu, 12 Feb 2015 08:37:34 +0100 :    0 newsletter emails have been sent.
  Thu, 12 Feb 2015 08:37:34 +0100 : The following email-addresses failed:

what should i do ?

**Comment by azine** [comment]
Hi,

can you post the swiftmailer-sections and the azine-email-bundle-sections from your config.yml and from your config_prod.yml?!

Cheers,
d.

**Comment by roozbeh360** [comment]
`
swiftmailer:
    default_mailer: default
    mailers:
        default:
            transport: "%mailer_transport%"
            host:      "%mailer_host%"
            username:  "%mailer_user%"
            password:  "%mailer_password%"
            spool:     { type: memory }
            port: 587
`

email bundle : 


`

azine_email:

    # the class of your implementation of the RecipientInterface
    recipient_class:      Shaygan\UserBundle\Entity\User # Required

    # the fieldname of the boolean field on the recipient class indicating, that a newsletter should be sent or not
    recipient_newsletter_field:  newsletter

    # the service-id of your implementation of the nofitier service to be used
    notifier_service:     azine_email.example.notifier_service

    # the service-id of your implementation of the template provider service to be used
    template_provider:    azine_email.example.template_provider # Required

    # the service-id of the implementation of the RecipientProviderInterface to be used
    recipient_provider:   azine_email.default.recipient_provider

    # the service-id of the mailer service to be used
    template_twig_swift_mailer:  azine_email.default.template_twig_swift_mailer
    no_reply:             # Required

        # the no-reply email-address
        email:                no-reply@example.com # Required

        # the name to appear with the 'no-reply'-address.
        name:                 notification daemon # Required

    # absolute path to the image-folder containing the images used in your templates.
    image_dir:            %kernel.root_dir%/../vendor/azine/email-bundle/Azine/EmailBundle/Resources/htmlTemplateImages/

    # list of folders from which images are allowed to be embeded into emails
    allowed_images_folders:  []

    # newsletter configuration
    newsletter:

        # number of days between newsletters
        interval:             14

        # time of the day, when newsletters should be sent, 24h-format => e.g. 23:59
        send_time:            10:00

    # templates configuration
    templates:

        # wrapper template id (without ending) for the newsletter
        newsletter:           AzineEmailBundle::newsletterEmailLayout

        # wrapper template id (without ending) for notifications
        notifications:        AzineEmailBundle::notificationsEmailLayout

        # template id (without ending) for notification content items
        content_item:         AzineEmailBundle:contentItem:message

    # the parameter to be used do identify campaigns in urls
    campaign_param_name:  pk_campaign # defaults work with piwik, but you can change them to work with adWords

    # the parameter to be used do identify campaign-keywords in urls
    campaign_keyword_param_name:  pk_kwd # defaults work with piwik, but you can change them to work with adWords

    # number of days that emails should be available in web-view
    web_view_retention:   90

    # the service-id of your implementation of the web view service to be used
    web_view_service:     azine_email.example.web_view_service


`

**Comment by azine** [comment]
Hi,

in your config.yml you configure only the "default" swiftmailer. So your change to use `immediateMailer: "@mailer"` is correct.

For the `azine_email:`-part: you only need to write the stuff in your config.yml that you want to override. I see most of what you use are defaults.

Can you post relevant log-output from Symfony => app/logs/prod.log or app/logs/dev.log and from your web-server log. Are there any exceptions in the logs?

Did you create the notification- and the sent_email-table? 

Does your implementation of `getNewsletterRecipientIDs` in your RecipientProviderInterface return some users?

You write that you want to send notifications. `emails:sendNewsletter` will send a newsletter, not notifications. Notifications are sent with the command `emails:sendNotifications` if any Notifications exist in the notification-table in your database.

Cheers,
D.

**Comment by roozbeh360** [comment]
thank you !

i see this in my log : 

[2015-02-12 10:33:45] app.WARNING: The newsletter for 'admin <baabakaan@remake.ir>' has not been sent. It would have been empty. {"subject":"_az.email.newsletter.subject","contentItems":[]} []

by the way 
how can i send notification ?

**Comment by azine** [comment]
Hi,

you're welcome.

To send a notification, create a notification-entity and run the `emails:sendNotifications` command.

Cheers,
d.

**Comment by roozbeh360** [comment]
thanks again !
but my problem not solve yet !

i still need send

**Comment by roozbeh360** [comment]
thanks again !
but my problem not solve yet !

i still need send Newsletter

[2015-02-12 10:33:45] app.WARNING: The newsletter for 'admin baabakaan@remake.ir' has not been sent. It would have been empty. {"subject":"_az.email.newsletter.subject","contentItems":[]} []

**Comment by azine** [comment]
Well as the log says. As the newsletter would have been empty, it was not sent. 

To change this, you need to implement a logic to create some content items (https://github.com/azine/email-bundle#2-the-content-item-templates) for your recipents.

You must implement your version of AzineNotifierService. 

ContentItems that are the same for all recipients => Azine\EmailBundle\Services.AzineNotifierService::getNonRecipientSpecificNewsletterContentItems() 
ContentItems that are different for each recipient => Azine\EmailBundle\Services.AzineNotifierService::getRecipientSpecificNewsletterSubject()

See ExampleNotifierService.php for an example what you should/could do in those functions.

Cheers,
d.

**Comment by azine** [comment]
PS: I updated the readme.md => https://github.com/azine/email-bundle#customise-the-content-of-you-emails

**Comment by roozbeh360** [comment]
thanks .

i will test it hope to figure out how to use this magnificent bundle .
if so i will help improve documents .

**Comment by roozbeh360** [comment]
hi

thanks for this magnificent bundle 

there is one more thing 

 Variable "username" does not exist in "AzineEmailBundle::baseEmailLayout.tx  
  t.twig" at line 6  

where should i pass username Variable to template ?

**Comment by azine** [comment]
Hi,

I removed this impediment/requirement from the baseEmailLayout.*.twig files. With the "head" version of the bundle you don't need to define the username anymore.

Your questions suggests, that you did not (yet) create your own sub-template. In the emails you'd send, there would be a "default-header-section" saying "Add some content here". I don't think you want that. ;-) 

You should create you own .html.twig and .txt.twig template that outputs your content(header). See
the two "exampleEmailLayout.*.twig"-files I just added to the bundle.

Cheers,
d.

PS: I'd be happy to hear if/when you succeeded with everything. And feedback on what needs more documentation is also welcome.
