### ISSUE TITLE
Upgrade to Swiftmailer 6

### ISSUE THREAD

**Issue by tacman** [azine/email-bundle#39]
Unfortunately, it appears that Swiftmailer 6 changed how messages are instantiated, with no deprecation period.  Now it is

    $message = (new \Swift_Message('Subject of Email'))

instead of

     $message = \Swift_Message::newInstance()
          ->setSubject('Subject of Email')

This only shows up twice in the bundle, but not sure how this should be dealt with.  Maybe with versioning?  A 4.0 tag? (The 3.0 tag was from Jan, 2017).

**Comment by azine** [comment]
resolved with #42
