### ISSUE TITLE
Ideas for extending SendEmail/Notification Entities

### ISSUE THREAD

**Issue by Kalyse** [azine/email-bundle#44]
Hey, 

What ideas would you have to make it possible to extend/override SendEMail and Notification entity classes?

For example, I'd like to be able to add additional fields when creating in my services.

**Comment by azine** [comment]
Hi,
I didn't put any thought into this yet. What would you want to add?

**Comment by Kalyse** [comment]
The only way this would really be possible is if you use a mappedSuperclass definition on the  `Notigication.orm.yml` entity. 

The reason for additional fields will be things like:

- Our application is multi tenanted, so we'd need to assign the notifications to a single tenant when created. 
- Our application uses UUID instead of (int) for the receipient_id 
- Our application needs to track other metrics when a notification is triggered. 

Issue, I see, is that if we were to turn Notification.orm.yml into a MappedSuperclass it would cause  a non-BC breakage. I could do the work on it, but might be a hard sell to get it merged.

**Comment by Kalyse** [comment]
I think you can close this issue. I'm probabaly going to run into too many "specific" requirements. 

As a suggestion, the way that FOS User Bundle handles the mappedSuperclass is probabaly what you want, with reagrds to the Notification entities. 

For example:

They have 

```
fos_user:
    user_class:     Application\Sonata\UserBundle\Entity\User
```

That's how I handle it. It would be possibel to do something similar with this bundle by turning the "Notification" into a mappedSuperclass. I actually had this working without an issue.

What you would have is you existing:

`Notification -> abstract NotificationBase (mappedSuperclass)`

Then each person can implement their own Notification class. All you'd need to do is extend the NotificationBase and update the setting on the bundle.

**Comment by azine** [comment]
Yes, I saw the "mappedSuperclass" option as well and use in in other places too.

Feel free to fork and maybe I can merge features you need back into this bundle?!

You can still use your fork in composer with an [inline alias](https://getcomposer.org/doc/articles/aliases.md#require-inline-alias).
